### ISSUE TITLE
Standardize UTC Handling Across Backend and WebUI

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#580]
**Overview**
Update the backend to handle datetime values in UTC. Ensure that both the scheduler and the WebUI adjust these times based on the timezone.

**Tasks**
- [ ] Implement server-side functionality to handle datetime values in UTC.
- [ ] Add a GET `/api/v0/config` API endpoint to return datetime settings from the server side.
- [ ] Modify the WebUI to detect and convert UTC datetime values to the local timezone.
- [ ] Modify the WebUI to parse cron schedules based on the server's timezone.

**Additional Context**
- #551
